### PR TITLE
Expose the type tag of a CodecRouter

### PR DESCRIPTION
**Pull request by etorreborre**
@bryce-anderson this is necessary for me to implement the following function
```scala
  // create a PATCH route from the POST route, just changing the
  // Method and Response body
  def createPatchRoute[T <: HList](route: RhoRoute[T]): RhoRoute[T] =
    ???
```

In the implementation of this method I need to access the `CodecRouter` type tag and copy it to a modified `CodecRouter`. If I don't do this I get `Any` as the type of the body.

Note that the whole thing is a work-around because I was not able to abstract some code between similar POST and PATCH routes without losing the precise response types.

### CODE REVIEW

**Comment by bryce-anderson** [comment]
I feel like there must be a better way to do this than exposing the `TypeTag`. Maybe changing the HTTP method is generally useful and we could provide a method on `RhoRoute` to do that?

**Comment by etorreborre** [comment]
This is possibly useful indeed. I'll try to do that instead.

**Comment by etorreborre** [comment]
This simplifies my code actually quite a bit. Thanks for the suggestion @bryce-anderson.

**Comment by bryce-anderson** [comment]
@etorreborre: can we close this PR? Sounds like you've found a better option.

**Comment by etorreborre** [comment]
@bryce-anderson the better option *is* in the PR :-). I amended it with a `withMethod` method to be able to set a new method on a `RoutingEntity` without having to expose the `TypeTag`.

**Comment by bryce-anderson** [comment]
I don't know how I missed that, sorry! This LGTM, thanks!

**Pull request merged**
