### PR TITLE
Don't encode case class AnyVals as RefProperty

### PR DESCRIPTION
**Pull request by jcranky**

### CODE REVIEW

**Comment by jcranky** [comment]
This should be the last one for now, with this, rho-swagger works properly for us :)

**Comment by rossabaker** [comment]
Release with this and #146, then?

**Comment by bryce-anderson** [comment]
@rossabaker, sounds like a plan to me.

cc @etorreborre, might want to take a quick peak in cause you have objections.

**Comment by etorreborre** [comment]
@bryce-anderson no objections I've already discussed this with @jcranky as we are on the same team :-).

**Comment by jcranky** [comment]
@bryce-anderson thanks !

**Comment by bryce-anderson** [comment]
v0.13.1 is off to central. Thanks again @jcranky!

**Comment by jcranky** [comment]
thanks :D

**Pull request merged**
