### PR TITLE
Fix handling the 'required' attribute of query parameters

### PR DESCRIPTION
**Pull request by jcranky**

### CODE REVIEW

**Comment by bryce-anderson** [comment]
Thanks for the PR @jcranky, it looks great.

**Comment by jcranky** [comment]
@bryce-anderson thanks :) 
Question: how frequently is `rho-swagger` released?

**Comment by rossabaker** [comment]
I'll release tonight if nobody beats me to it.

**Comment by jcranky** [comment]
@rossabaker awesome, thanks :D

**Pull request merged**
