### PR TITLE
Fixes #210 Complex types should be added as strings

### LINKED ISSUE #210: Complex types should not be used in Swagger's parameters located in path or query
The parameter object is specified at https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object

The following code: 
```
    GET / "crazyPathVar" / pathVar[Foo] |>>  { (_:Foo) => NoContent() }
    GET / "crazyParam" +? param[Foo]("foo")    |>>  { (_:Foo) => NoContent() }
```
results in a swagger.json not conforming to the specification:
```
{
  "swagger" : "2.0",
  "info" : {
    "version" : "1.0.0",
    "title" : "My API"
  },
  "paths" : {
    "/crazyPathVar/{rho.test.rhotest.foo}" : {
      "get" : {
        "tags" : [ "crazyPathVar" ],
        "operationId" : "getCrazyPathVar-rho.test.rhotest.foo",
        "parameters" : [ {
          "name" : "rho.test.rhotest.foo",
          "in" : "path",
          "required" : true,
          "type" : "Foo"
        } ],
        "responses" : {
          "204" : {
            "description" : "No Content"
          }
        }
      }
    },
    "/crazyParam" : {
      "get" : {
        "tags" : [ "crazyParam" ],
        "operationId" : "getCrazyParam-foo",
        "parameters" : [ {
          "name" : "foo",
          "in" : "query",
          "required" : true,
          "$ref" : "Foo"
        } ],
        "responses" : {
          "204" : {
            "description" : "No Content"
          }
        }
      }
    }
  },
  "definitions" : {
    "Unit" : {
      "type" : "object",
      "description" : "Unit"
    },
    "Foo" : {
      "type" : "object",
      "required" : [ "a", "b" ],
      "properties" : {
        "a" : {
          "type" : "string"
        },
        "b" : {
          "type" : "string"
        }
      },
      "description" : "Foo"
    }
  }
}
```
The `parameters` for the crazyPathVar is incorrect, because the `type` is `"Foo"`and according to the specification for the `type`: 
"Since the parameter is not located at the request body, it is limited to simple types (that is, not an object). The value MUST be one of "string", "number", "integer", "boolean", "array" or "file" "

The parameters for the `crazyParam` is incorrect, because:
 * `"$ref" : "Foo"` doesn't point to the declaration of Foo type
 * there is no `type` while it is a required field

IMO rho should attempt to map the type of a pathVar / param to one of "string", "number", "integer", "boolean", "array" or "file" and if not possible fall back to "string" since it is the least restrictive of the types.

### PR DESCRIPTION
**Pull request by eklavya**

### CODE REVIEW

**Comment by jcranky** [comment]
I'm not sure I understand the consequences of that. You don't want the type name in swagger file?

**Comment by jcranky** [comment]
ignore my question, LGTM

**Comment by bryce-anderson** [comment]
Thanks @eklavya! Sorry for taking so long on this. I'm not getting email updates about it, which is a bit annoying.

**Comment by eklavya** [comment]
Thanks for your time @bryce-anderson @jcranky :)

**Pull request merged**
