### PR TITLE
Add support for user-provided route tags.

### LINKED ISSUE #314: Feature request: Allow customizing tags for generated operations
The models builder [currently defaults](https://github.com/http4s/rho/blob/master/swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala#L232) to using the first segment of an operation's path as its tag. Those tags are used as headings by the Swagger UI to group related routes together. My team follows a pattern of using an `/api` prefix for everything other than status checks, so we end up with one big block of routes in the UI:
Screen Shot 2019-05-01 at 1 56 46 PM
Ideally, we'd like to be able to override the tags to manually group things ourselves.

I'd be happy to contribute this change, as long as it hasn't been left out for a reason.

### PR DESCRIPTION
**Pull request by danxmoran**
Fixes #314.

I went with `@@` for the syntax to get things rolling, but I'm not tied to it. I plan to have a follow-up PR that adds alphanumeric aliases for it and the other existing methods as part of #315.

### CODE REVIEW

**Comment by zarthross** [comment]
I'll think on the symbolic operator as well.  I have some time tomorrow night, I'll give this a good review then.  Thanks for the PR!

**Comment by zarthross** [comment]
@danxmoran If you good with the current PR I'll happily merge it in.

**Comment by danxmoran** [comment]
Agreed that the mismatched operator precedence is annoying, but I'm ok with having it merged as-is :+1: thanks for the review!

**Comment by danxmoran** [comment]
@zarthross sorry to bother, is there anything else I can do to help get this merged?

**Comment by zarthross** [comment]
@danxmoran I was waiting for some other maintainers to comment, but seeing how no one has... i'll just merge it anyways.  It'll get released with our next milestone.

**Pull request merged**
