### PR TITLE
Http4s 0.23 (Cats 3)

### PR DESCRIPTION
**Pull request by zarthross**

### CODE REVIEW

**Comment by balthz** [comment]
Is there by any chance an ETA for this? Just asking because I'm trying to upgrade my project to CE3 and looking at https://github.com/typelevel/cats-effect/issues/1330, this one here is missing for me to roll up my sleeves and get the transition going :)

**Comment by zarthross** [comment]
As long as you aren't looking for Scala 3 support, I can get the CE3 support released as a RC1 soon.  Scala3 is going to require a complete rewrite.

**Comment by zarthross** [comment]
I'm going to aim to release this and https://github.com/http4s/rho/pull/548 released as an RC1 this week.  If someone wants to work on documentation for the header changes, let me know!  That's a piece that's missing.

**Comment by zarthross** [comment]
@balthz this is one its way out to maven now.  Let me know if you have any trouble.

**Comment by balthz** [comment]
> @balthz this is one its way out to maven now. Let me know if you have any trouble.

Thank you a lot!!

**Pull request merged**
