### PR TITLE
Upgrade to http4s 0.16.5, Fixes #204

### LINKED ISSUE #204: Release a http4s-0.16 compatible version
Can we release a version of rho compatible with http4s-0.16. This is the final scalaz version of http4s, so I imagine a lot of people will be stuck on it for a while.

Of the versions of rho on maven central, 0.16.2 was built against http4s-0.15, then the next version 0.17 jumps to http4s-0.17.

### PR DESCRIPTION
**Pull request by wongelz**
Upgrades the existing release-0.16.x branch to latest scalaz version of http4s (0.16.5).
Need to decide on a version number and create a new branch to merge into (if different branch is desired).

### CODE REVIEW

**Comment by bryce-anderson** [comment]
I won't be able to look at this in depth until the weekend but I don't foresee any problems other than picking a version number. I don't really like the idea of continuing with 0.16 but 0.17 of already taken. I'm wide open to suggestions, or could also be convinced of `0.16something`.

**Comment by jcranky** [comment]
`0.16.16`? This is an awkward situation :)

**Comment by bryce-anderson** [comment]
(lets not merge this until we get the destination sorted)

**Comment by rossabaker** [comment]
I think as the next version of 0.16 is the least awkward option.  It's what people would _expect_ an 0.16 to be.  Anybody on 0.15 of http4s is on an unsupported version.  And it's sequential with the dependency.

**Comment by bryce-anderson** [comment]
I'll buy that. I'll merge this commit as is this evening barring objections.

**Comment by bryce-anderson** [comment]
Thanks for the PR @wongelz! I presume you're interested in a release?

**Comment by wongelz** [comment]
Thanks. Yes please!

**Comment by bryce-anderson** [comment]
One thing I just noticed a little late is that the rho version was also bumped to 0.16.5 when the next of the series should be 0.16.3. Any reason not to release this as 0.16.3?

**Comment by wongelz** [comment]
I just made it 0.16.5 to match the version of http4s, feel free to change it to 0.16.3.

**Comment by rossabaker** [comment]
By the way, there's an http4s-0.16.6.  Might as well get current while we're here.

**Comment by bryce-anderson** [comment]
@wongelz, I'll bump the http4s version and try to cut a release this
evening.

**Pull request merged**
