### PR TITLE
Added type: "object" to generated object types

### PR DESCRIPTION
**Pull request by reactormonk**
Apparently that's the proper way to go.

### CODE REVIEW

**Comment by bryce-anderson** [comment]
Do you mind pointing me to the section of spec that defines this? I'm sure its right, and I'll look it up later, but if you find the time before I do, I'd appreciate it. 😄

**Comment by reactormonk** [comment]
There isn't but the validator here is a bit picky. It should be correct in all cases where there's a `properties` field, so it shouldn't hurt.

**Comment by bryce-anderson** [comment]
Sounds good to me. Sorry for the delay: I need to work out a better notification mechanism, these keep slipping through.

**Comment by reactormonk** [comment]
... I tried messing around with `sonatypeRelease`, but apparently it's not that easy. You still gotta release manually.

**Comment by bryce-anderson** [comment]
Its released and tagged as 0.16.2.

**Pull request merged**
