### PR TITLE
Use MUnit in `rho-core` tests

### PR DESCRIPTION
**Pull request by danicheg**
The main goal of this PR is a unification of the test framework in `http4s`'s projects.

### CODE REVIEW

**Comment by danicheg** [comment]
@zarthross if you can check that would be great. 🙏🏻

**Comment by zarthross** [comment]
@danicheg  I should be able to find some time to look over it tonight, sorry about the delay.

**Review by zarthross — APPROVED** [review]
Was a rather large diff, but a quick look over I didn't see any issues. 

It would be nice to see a future refactor that integrated munit cats effect and got rid of the `unsafeRunSync`s littered throughout the tests.

 Thanks for the hard work!

**Comment by danicheg** [comment]
@zarthross and it's done #568

**Pull request merged**
