### PR TITLE
Fix generation of swagger for alternative routes (routes with || )

### PR DESCRIPTION
**Pull request by RafalSumislawski**
This is a fix for #448. 

There are already tests ("find a simple or-path" and "find a capture or-path") which exercise the scenario leading to this issue, but due to the way the assertions are formulated the problem is not detected. Redefinition of these tests is also part of this PR.

The issue actually has impact not only on tags, but generally on every difference between the alternatives defined with `||` . The root cause of the issue is that `SwaggerModelsBuilder.mkOperation` works on a `RhoRoute`, while a single `RhoRoute` may represent more than one operation in swagger model. Information belonging to these alternative operations gets mixed up. The solution is to split single `RhoRoute` into multiple routes, each representing one of the alternatives (I named them `LinearRoute`s) and then building the operation basing on these. This is more or less what `collectPaths -> mkPathStrs -> linearizeStack` call chain already does, but the distinction between alternative paths is somewhat lost instead of being propagated to `mkOperation`. 

The fix itself (see first commit) is relatively simple, but it requires modifying the signature of `mkOperation` and that method is used 28 times in tests. So the real challenge here was to implement the fix in a way which would not make the tests overly complicated/verbose. Hence the sizeable refactor in the second commit.

### CODE REVIEW

**Comment by RafalSumislawski** [comment]
I think this PR may also fix the #165. At least the swagger-not-working-well part. It obviously doesn't solve the do-we-even-need-this-feature part.

**Comment by RafalSumislawski** [comment]
Hi @zarthross 
Is there anything more I should do about this (and the others) PR before it can be merged? I think the Binary Compatibility has nothing to do with the changes in this PR, but if that's a blocker, I can try doing something about it.

**Review by zarthross — APPROVED** [review]

**Comment by zarthross** [comment]
Hey, sorry for the delay... lots of things have come up for me... I'll dedicate some time this week to getting your PRs rolled out into a release.

**Comment by zarthross** [comment]
Release in https://github.com/http4s/rho/releases/tag/v0.21.0-RC2 should be rolling out to mvn central now

**Pull request merged**
