### PR TITLE
WIP Scala 2.13.0-M5

### PR DESCRIPTION
**Pull request by zarthross**

### CODE REVIEW

**Comment by zarthross** [comment]
Good call-out.   I was already considering making uses of Seq explicitly immutable.. so, i'll just go ahead and do that.

**Comment by rossabaker** [comment]
Just a note on roadmap: We'll keep http4s-0.20 on M5, and target http4s-0.21 for the release of 2.13.0-final.  If we can get a milestone out on RC2 beforehand, we will.

**Comment by RafalSumislawski** [comment]
Hi @zarthross 
I see there was no progress on this recently. Maybe I could help and pick it up where you left off?

**Comment by RafalSumislawski** [comment]
or is the plan to merge #324 instead?

**Comment by zarthross** [comment]
This branch, right now mainly has changes from `scala.collection.Seq` to `scala.collections.immutable.Seq` which I think it still something we want for the next version of Rho, but I don't think is in that other PR.  I think I'll open a separate PR for that change and close this one in favor of the other.

**Comment by zarthross** [comment]
Scratch that, I forgot I already pulled those immutable seq fixes out of this PR.

**Pull request closed without merging**
