### PR TITLE
Cut 0.16.1

### PR DESCRIPTION
**Pull request by reactormonk**
Would be useful to have the changes as its own version.

### CODE REVIEW

**Comment by rossabaker** [comment]
Am I misreading this, or does this end up as an empty PR?

**Comment by bryce-anderson** [comment]
It looks like two commits: one that rolls back from `0.17.0-SNAPSHOT` to `0.16.1`, and another one that reverts that. I presume the first commit would get tagged.

Maybe it would be better to make a new branch, `release-0.16.1` out of the first commit, tag it, then delete it?

**Comment by reactormonk** [comment]
So merge this one, then add another PR to revert this PR? Or even just push the "revert this PR" button?

**Comment by reactormonk** [comment]
Sorry, I haven't read the `bin/travis` closely enough.

**Comment by reactormonk** [comment]
Should I just push a `release-0.16.x` branch directly into the rho repo?

**Comment by bryce-anderson** [comment]
Sounds fine to me.

**Comment by reactormonk** [comment]
Do you need to push the close button, or does travis do this?

**Comment by bryce-anderson** [comment]
I assumed you could do it. 😄 I've published it, should be in maven soon.

**Comment by reactormonk** [comment]
I think there's some sbt plugin that can do that too. I'll go look for it.

**Pull request closed without merging**
